# install the necessary packages for this repo
install.packages("tidyr")
install.packages("shiny")
install.packages("tidyverse")
install.packages("flexdashboard")
install.packages("devtools")
install.packages("plotly")
install.packages("hrbrthemes")
install.packages("GGally")
install.packages("viridis")
install.packages("forecast")
install.packages("glue")
devtools::install_github("kassambara/ggcorrplot")
install.packages('heatmaply')
install.packages("ggthemes")
